import Footer from "@/components/shared/footer";
import "@/styles/pagination.css";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/shared/Header";

export const metadata: Metadata = {
  title: "",
  description: "Generated by ",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <>{children}</>
        <Footer />
      </body>
    </html>
  );
}
